version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: staff_scheduler_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: staff_scheduler
      MYSQL_USER: scheduler_user
      MYSQL_PASSWORD: scheduler_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - staff_scheduler_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: staff_scheduler_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: scheduler_user
      PMA_PASSWORD: scheduler_password
    ports:
      - "8080:80"
    networks:
      - staff_scheduler_network

  backend:
    build: ./backend
    container_name: staff_scheduler_backend
    depends_on:
      - mysql
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: staff_scheduler
      DB_USER: scheduler_user
      DB_PASSWORD: scheduler_password
      SESSION_SECRET: your-super-secret-session-key-change-in-production
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASSWORD: your-app-password
      OPTIMIZATION_ENGINE: javascript
      CORS_ORIGIN: http://localhost:3000
      CORS_CREDENTIALS: true
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/reports:/app/reports
      - ./backend/uploads:/app/uploads
    command: npm run dev
    networks:
      - staff_scheduler_network

  frontend:
    build: ./frontend
    container_name: staff_scheduler_frontend
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:3001
      REACT_APP_APP_NAME: Staff Scheduler
      REACT_APP_VERSION: 1.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    networks:
      - staff_scheduler_network

volumes:
  mysql_data:

networks:
  staff_scheduler_network:
    driver: bridge
