/**
 * Creates one empty schedule period (shifts defined, nobody assigned yet).
 * Filling it is left entirely to AutoScheduleService, called by the
 * simulation's own round loop — nothing here pre-stages assignments.
 *
 * @author Luca Ostinelli
 */

import { Pool, ResultSetHeader } from 'mysql2/promise';

export async function createEmptySchedulePeriod(
  pool: Pool,
  departmentId: number,
  headUserId: number,
  name: string,
  startDate: string,
  endDate: string,
  employeeCount: number
): Promise<number> {
  const [schedRes] = await pool.execute<ResultSetHeader>(
    `INSERT INTO schedules (name, description, department_id, start_date, end_date, status, created_by)
     VALUES (?, '[SIM] generated by simulation harness', ?, ?, ?, 'published', ?)`,
    [name, departmentId, startDate, endDate, headUserId]
  );
  const scheduleId = schedRes.insertId;

  // Three 8h shifts/day, staffed at roughly 1 slot per ~14 employees per
  // shift so a roster of any size gets a plausible number of assignments
  // without every single employee working every single shift.
  const perShift = Math.max(2, Math.min(20, Math.ceil(employeeCount / 14)));
  const shiftTimes: Array<[string, string]> = [
    ['07:00:00', '15:00:00'],
    ['15:00:00', '23:00:00'],
    ['23:00:00', '07:00:00'],
  ];
  const start = new Date(startDate);
  const end = new Date(endDate);
  for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
    const day = d.toISOString().slice(0, 10);
    for (const [s, e] of shiftTimes) {
      await pool.execute(
        `INSERT INTO shifts (schedule_id, department_id, date, start_time, end_time, min_staff, max_staff, status)
         VALUES (?, ?, ?, ?, ?, ?, ?, 'open')`,
        [scheduleId, departmentId, day, s, e, Math.max(1, Math.floor(perShift * 0.6)), perShift]
      );
    }
  }
  return scheduleId;
}
